### ISSUE TITLE
Please use languagetool as a maven dependency

### ISSUE THREAD

**Issue by vatbub** [vogellacompany/languagetool-eclipse-plugin#5]
I have only a Windows PC and I fail to build the plugin as I can't execute shell scripts there. However, languagetool is available on maven central. My problem would be solved if you declared the dependency in your pom instead of using the sh-script. [More info here.](http://wiki.languagetool.org/java-api)

**Comment by vogella** [comment]
@vatbub Awesome, sorry for the late response I was busy with the EclipseCon Europe conference. I have a look right now.

**Comment by vatbub** [comment]
Hi, I actually already submitted a Pull Request which fixes the issue.

**Comment by vogella** [comment]
>  Hi, I actually already submitted a Pull Request which fixes the issue.

I know, that is what I mean: I have a look (at your PR) right now. Sorry for not  being clear about it.
